baseURL = 'https://smalakys.com/'
locale = 'en-us'
title = 'Linas Smalakys'
theme = 'hugo-book'

[params]
  BookFavicon = 'adventures.svg'
  BookTheme = 'auto'

[caches]
  [caches.images]
    dir = ':cacheDir/images'