baseURL = 'https://smalakys.com/'
locale = 'en-us'
title = 'Personal Website'
theme = 'hugo-book'

[params]
  BookFavicon = 'objectives.svg'
  BookTheme = 'dark'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
